#!/bin/bash
lista=$(find /home/mswiders/Documents/projekt-zespolowy/APP/MAGSOFT/ -maxdepth 8 -type f)
#lista=$(find . -maxdepth 3 -type f)

#lista=$(find /home/mswiders/testowy/ -type f)
for plik in $lista
do
	perl -pi -e 's/MAGSOFT/VIDSOFT/g' $plik
	
done
